"""
@author: qwattash - Alfredo Mazzinghi
@license GPLv2
(based on django's autogenerated files)
"""

from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'vrserver.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^uclvr/', include('sfmmanager.urls')),
)
